# Generated by Django 4.0.4 on 2022-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Your Name')),
                ('contact', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=30, verbose_name='Your Email Address')),
                ('query', models.CharField(max_length=1000, verbose_name='Your Name')),
            ],
        ),
    ]
